### ISSUE TITLE
All maps: include option to select region: Vlaanderen, Wallonie, Brussels hoofdstedelijk gewest. By default all 3 selected. First INBO needs to add extra column indicating in which region the observation/reporting is

### ISSUE THREAD

**Issue by mvarewyck** [inbo/alien-species-portal#37]

**Comment by SanderDevisscher** [comment]
@damianooldoni can you provide @mvarewyck with a list of 10x10km gridcells by region (flanders, brussels, wallonia) ?

**Comment by mvarewyck** [comment]
@damianooldoni I will also need it for the 1x1 km gridcells

**Comment by damianooldoni** [comment]
I will, sure. I have some specs related questions:
1. My idea is to add three columns `isFlanders`, `isWallonia`, `isBrussels` to the existing grid files with `TRUE`/`FALSE` values. Do you agree on this? If yes, can you point to the files I need to work on? Are you maybe using the ones from TrIAS indicators: https://github.com/trias-project/indicators/tree/main/data/external/utm1_bel and https://github.com/trias-project/indicators/tree/main/data/external/utm10_bel ? If so, I will place the modified files to another directory as by definition any modified file cannot remain in `./external`
2. Is the code I write to add these columns of any interest and so must be public somewhere? If yes, let me know where you prefer I put it. Otherwise, I think I will put it somewhere in trias indicators repo (but at the moment without publishing on correspondent GitHub Pages website)
3. I will assign grid cells containing the regional borders to multiple regions (`TRUE` values). Is it ok to you?

**Comment by SanderDevisscher** [comment]
First & foremost I was "falsely" under the impression you did a similar exercise already.  

> I will, sure. I have some specs related questions:
> 
> 1. My idea is to add three columns `isFlanders`, `isWallonia`, `isBrussels` to the existing grid files with `TRUE`/`FALSE` values. Do you agree on this? If yes, can you point to the files I need to work on? Are you maybe using the ones from TrIAS indicators: https://github.com/trias-project/indicators/tree/main/data/external/utm1_bel and https://github.com/trias-project/indicators/tree/main/data/external/utm10_bel ? If so, I will place the modified files to another directory as by definition any modified file cannot remain in `./external`

I my opinion adding those 3 column should be sufficient. We use the same files but downloaded directly from eea (therefor they are not UTM but EEA reference grids).  @mvarewyck what do you think ?

> 2. Is the code I write to add these columns of any interest and so must be public somewhere? If yes, let me know where you prefer I put it. Otherwise, I think I will put it somewhere in trias indicators repo (but at the moment without publishing on correspondent GitHub Pages website)

These grids could be of interest to many Belgium regional issues therefor I think it would be good to place them somewhere publicly accessible. Currently the grids are placed [here](https://github.com/inbo/alien-species-portal/tree/mockup/alienSpecies/inst/extdata/grid) in this public repository but we intend to move them, along with all the other data, to a S3 bucket for more streamlined updating. A more sustainable publicly accessible location is thus advised. 

> 3. I will assign grid cells containing the regional borders to multiple regions (`TRUE` values). Is it ok to you?

@mvarewyck what do you think ?

**Comment by damianooldoni** [comment]
@SanderDevisscher: me too, but what I did was just restricted to protecte areas so it was quite hard coded. Any how, it's something I can do of course. Or maybe @jrhillae did it already in the context of LIFE RIPARIAS dashboard?
 
Publishing them to zenodo could be also interesting. Could also be nice to use geojson format as it is way more open than GIS shapefiles and also you have one (1!) file instead of oh so many 😄 Some more info about geoJSON and how easy it is to use such format, you can find on the INBO tutorial: https://inbo.github.io/tutorials/tutorials/spatial_standards_vector/

**Comment by mvarewyck** [comment]
> > 1. My idea is to add three columns `isFlanders`, `isWallonia`, `isBrussels` to the existing grid files with `TRUE`/`FALSE` values. Do you agree on this? If yes, can you point to the files I need to work on? Are you maybe using the ones from TrIAS indicators: https://github.com/trias-project/indicators/tree/main/data/external/utm1_bel and https://github.com/trias-project/indicators/tree/main/data/external/utm10_bel ? If so, I will place the modified files to another directory as by definition any modified file cannot remain in `./external`
> 
> I my opinion adding those 3 column should be sufficient. We use the same files but downloaded directly from eea (therefor they are not UTM but EEA reference grids). @mvarewyck what do you think ?
> 

These 3 columns are sufficient. As @SanderDevisscher mentioned, we extract the shape files from [EEA](https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2)

> > 3. I will assign grid cells containing the regional borders to multiple regions (`TRUE` values). Is it ok to you?
> 
> @mvarewyck what do you think ?

Yes, this is fine. The user will select one or more regions (isFlanders, isWallonia, isBrussels) in the app. Based on this selection we will determine the unique grids that should be shown in the plot.

> Could also be nice to use geojson format as it is way more open than GIS shapefiles and also you have one (1!) file instead of oh so many

Conversion to geojson format is perfectly fine. We also use it for other projects to have this file reduction.

**Comment by damianooldoni** [comment]
I think I solved this issue. Please, @SanderDevisscher and @mvarewyck, can you:
1. open the three Geopackages in `data/output` mentioned in https://github.com/trias-project/indicators/pull/119 and check whether they fulfill your expectations
2. successfully reproduce the workflow (Rmd) mentioned in https://github.com/trias-project/indicators/pull/119

@SanderDevisscher is the official reviewer just because he is member of the trias-project GitHub organisation.

**Comment by mvarewyck** [comment]
@damianooldoni Thanks, this works perfectly at our side.

@SanderDevisscher Two more questions on this:
1. Do we need to restrict only the map to the selected regions or also the other plots? E.g. barplot (with time selector) on Species information > Observations page
2. Do we also need to include this filter option for region (Flanders, Wallonia, Brussels) on the management page for e.g. Lithobates catesbeianus? The current page shows a map with occurrences for all regions together with cpue in Flanders only.

**Comment by SanderDevisscher** [comment]
> @damianooldoni Thanks, this works perfectly at our side.
> 
> @SanderDevisscher Two more questions on this:
> 
> 1. Do we need to restrict only the map to the selected regions or also the other plots? E.g. barplot (with time selector) on Species information > Observations page

I think its best to see it as a filter for the "global" indicators and as a category for the bar plot on species information ea different colors for the different regions. @timadriaens @bramdhondt what do you think ? 

> 2. Do we also need to include this filter option for region (Flanders, Wallonia, Brussels) on the management page for e.g. Lithobates catesbeianus? The current page shows a map with occurrences for all regions together with cpue in Flanders only.

I think this merits a discussion. In the current version of bullfrog and ruddy duck management only part of the flemish management is included. I think allowing users to filter based on regions will highlight the lack of info about management in Wallonia or maybe this is already the case as is.  I hope data about bullfrog management in Wallonia will become freely available in the future. @timadriaens @bramdhondt what do you guys think about implementing a region filter on management ?

**Comment by b-dhondt** [comment]
@SanderDevisscher - "what do you guys think about implementing a region filter on management ?" Since it is likely that a lot of information is gathered at regional level only, I think implementing a region filter makes sense, as the highlighted data is then closer to reality.

**Comment by mvarewyck** [comment]
I will include a filter then for the regions at the top of the management page.
Trend plot will have a single line per selected region (instead of just flanders).
For Lithobates, the filter will be repeated for the barplot at the bottom

@SanderDevisscher Could you add to the shape files `communes.geojson` and `provinces.geojson` [here](https://github.com/inbo/alien-species-portal/tree/mockup/alienSpecies/inst/extdata)
* a single region column  (flanders, wallonia, brussels)
* add communes and provinces for the other regions (wallonia & brussels)

**Comment by mvarewyck** [comment]
As discussed during meeting.

TODO for management page: include black border for 'gewest' if 'provinces' is selected.
