### ISSUE TITLE
Create indicators filter

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#8]
![image](https://user-images.githubusercontent.com/16779320/143435427-a6f62514-cf54-4f0a-9ebb-63abfdde80b2.png)

Een gebruiker zou de [GRIIS](https://www.gbif.org/dataset/6d9e952f-948c-4483-9807-575348147c7e) - checklist aangevuld met de soorten van de [List of Invasive Alien Species of Union concern](https://ec.europa.eu/environment/nature/invasivealien/list/index_en.htm) die nog niet voorkomen in België<sup>1</sup> moeten kunnen filteren op de volgende velden:

### Deze filters zouden steeds zichtbaar moeten zijn met een weergave van de selectie.
- [ ] Taxa: meerkeuze: Naast het soort niveau moet de gebruiker ook kunnen filteren op Klasse, Orde en Familie.
- [ ] Habitats: meerkeuze:
- [ ] Pathways: meerkeuze: Een gebruiker moet zowel kunnen filteren op lvl1 als lvl2 pathways
- [ ] Degree of establishment: meerkeuze:
- [ ] Country of origin: meerkeuze: 

### Deze filters worden weergegeven als de gebruiker op _more_ drukt
- [ ] Jaren: slider: default 1830 - nu. filtert op year of first introduction.
- [ ] Region: meerkeuze: VLA, WAL, BXL, BEL (= default) 
- [ ] Sources: meerkeuze:

De filters zouden van toepassing moeten zijn op alle grafieken en tabellen vervat onder het indicatoren hoofdstuk. 
Alle filters hebben als default waarde "alles".
De gebruiker moet in staat zijn de gekozen filters op te slaan (ik geloof dat we besproken hebben, als query in de url, klopt dit?)

<sup>1</sup> @peterdesmet @damianooldoni zitten de soorten van de [List of Invasive Alien Species of Union concern](https://ec.europa.eu/environment/nature/invasivealien/list/index_en.htm) die nog niet voorkomen in België reeds vervat in de checklist of moeten we die er nog aan hangen ?

**Comment by peterdesmet** [comment]
@SanderDevisscher nee, de lijst bevat enkel soorten die in België voorkomen

**Comment by SanderDevisscher** [comment]
@mvarewyck @dbemelmans @eadriaensen kunnen jullie deze logica al opstellen o.b.v. de [GRIIS](https://www.gbif.org/dataset/6d9e952f-948c-4483-9807-575348147c7e) - checklist ?
Ondertussen bespreek ik met @timadriaens of en hoe we de unielijst soorten die niet in België voorkomen zullen toevoegen (zie #10)

**Comment by mvarewyck** [comment]
Previously there was a 'Union list' filter to filter only EU concern species versus all species. Is this still needed?

**Comment by mvarewyck** [comment]
I've implemented the query filter for habitats. To be implemented for the other filters.

**Comment by peterdesmet** [comment]
I'll let @SanderDevisscher or @timadriaens decide if a filter on EU concern species is necessary, but you can find a curated csv file of those species at https://github.com/riparias/union-list/blob/main/data/processed/taxon.csv

**Comment by timadriaens** [comment]
@damianooldoni asked me to update the one here [https://github.com/trias-project/indicators/blob/master/data/input/eu_concern_species.tsv](https://github.com/trias-project/indicators/blob/master/data/input/eu_concern_species.tsv) with the recent addition of the 22 species, so that one is more updated.

**Comment by damianooldoni** [comment]
Yes, indeed. I asked @timadriaens to not change it in the [riparias/union-list](https://github.com/riparias/union-list/) repo because the EU concern species list doesn't contain such 22 species yet officially. As long as the official list will be changed I will try to incorporate the changes in [riparias/union-list](https://github.com/riparias/union-list/) and also trying to get the raw data from EASIN (see https://github.com/riparias/union-list/issues/6).

**Comment by mvarewyck** [comment]
@SanderDevisscher suggested to use the kingdom - phylum - class - order - family - species keys instead of their names for the URL query string. In which dataset can I find an overview of all these keys, i.e. key and corresponding name in the file [data_input_checklist_indicators.csv](https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/data_input_checklist_indicators.tsv) ?

**Comment by damianooldoni** [comment]
Simply there are not. I could add them as they are just a selection, see https://github.com/trias-project/indicators/blob/master/src/01_get_data_input_checklist_indicators.Rmd#L52-L61. 
Notice that all this information is the information as published within the unified checklist. These keys are not pointing to the higher taxonomy in the GBIF taxonomic backbone. The link to the backbone is at the taxon level via `nubKey`.

Just tell me "GO" and I will add such keys.

**Comment by mvarewyck** [comment]
> Simply there are not. I could add them as they are just a selection, see https://github.com/trias-project/indicators/blob/master/src/01_get_data_input_checklist_indicators.Rmd#L52-L61. 

Would it mean that if we have e.g. key 220 for **class** that this key number will not occur for any other taxonomic level (eg. kingdom, phylum..)? If so, I would prefer to add the keys to the data. If not, I don't think it will simplify the code a lot at our side.

**Comment by damianooldoni** [comment]
I mean that we will have extra fields; `classKey`, `phylumKey`, `orderKey`, `kingdomKey`, etc.
As any class, phylum, order or kingdom is a taxon itself, these keys are unique: so no `classKey` appearing as `kingdomKey` or `ordeKey` or any other kind of key. Said this, I think you can really get benefits out of this. Let me know.

**Comment by mvarewyck** [comment]
Thanks for explaining Damiano. Indeed, can you please add those key-columns to the data then?

**Comment by mvarewyck** [comment]
@damianooldoni For species I can use the gbif key?
